<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

-   Identify duplicate values in the dataset.

-   Remove duplicate values from the dataset.

-   Identify missing values in the dataset.

-   Impute the missing values in the dataset.

-   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [4]:
import pandas as pd

Load the dataset into a dataframe.

In [5]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")

## Finding duplicates

In this section you will identify duplicate values in the dataset.

 Find how many duplicate rows exist in the dataframe.

In [44]:
# your code goes here

duplicaterows = df[df.duplicated()]
len(duplicaterows)

0

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [10]:
# your code goes here
df.drop_duplicates(inplace=True)

Verify if duplicates were actually dropped.

In [12]:
# your code goes here
df.shape

(11398, 85)

## Finding Missing values

Find the missing values for all columns.

In [14]:
# your code goes here
import numpy as np
missing_data = df.isnull()
missing_data

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11547,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11548,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11549,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11550,False,False,False,False,False,False,False,False,False,True,...,False,True,False,False,False,False,False,False,False,False
11551,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

Find out how many rows are missing in the column 'WorkLoc'

In [15]:
# your code goes here
missing_data['WorkLoc'].value_counts()

WorkLoc
False    11366
True        32
Name: count, dtype: int64

In [16]:
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

Respondent
Respondent
False    11398
Name: count, dtype: int64

MainBranch
MainBranch
False    11398
Name: count, dtype: int64

Hobbyist
Hobbyist
False    11398
Name: count, dtype: int64

OpenSourcer
OpenSourcer
False    11398
Name: count, dtype: int64

OpenSource
OpenSource
False    11317
True        81
Name: count, dtype: int64

Employment
Employment
False    11398
Name: count, dtype: int64

Country
Country
False    11398
Name: count, dtype: int64

Student
Student
False    11347
True        51
Name: count, dtype: int64

EdLevel
EdLevel
False    11286
True       112
Name: count, dtype: int64

UndergradMajor
UndergradMajor
False    10661
True       737
Name: count, dtype: int64

EduOther
EduOther
False    11234
True       164
Name: count, dtype: int64

OrgSize
OrgSize
False    11302
True        96
Name: count, dtype: int64

DevType
DevType
False    11333
True        65
Name: count, dtype: int64

YearsCode
YearsCode
False    11389
True         9
Name: count, dtype: int64

Age1stCode
Age1stCode
False    11385
True        13
Name: count, dtype: int64

YearsCodePro
YearsCodePro
False    11382
True        16
Name: count, dtype: int64

CareerSat
CareerSat
False    11398
Name: count, dtype: int64

JobSat
JobSat
False    11397
True         1
Name: count, dtype: int64

MgrIdiot
MgrIdiot
False    10905
True       493
Name: count, dtype: int64

MgrMoney
MgrMoney
False    10901
True       497
Name: count, dtype: int64

MgrWant
MgrWant
False    10905
True       493
Name: count, dtype: int64

JobSeek
JobSeek
False    11398
Name: count, dtype: int64

LastHireDate
LastHireDate
False    11398
Name: count, dtype: int64

LastInt
LastInt
False    10985
True       413
Name: count, dtype: int64

FizzBuzz
FizzBuzz
False    11361
True        37
Name: count, dtype: int64

JobFactors
JobFactors
False    11395
True         3
Name: count, dtype: int64

ResumeUpdate
ResumeUpdate
False    11359
True        39
Name: count, dtype: int64

CurrencySymbol
CurrencySymbol
False    11398
Name: count, dtype: int64

CurrencyDesc
CurrencyDesc
False    11398
Name: count, dtype: int64

CompTotal
CompTotal
False    10589
True       809
Name: count, dtype: int64

CompFreq
CompFreq
False    11192
True       206
Name: count, dtype: int64

ConvertedComp
ConvertedComp
False    10582
True       816
Name: count, dtype: int64

WorkWeekHrs
WorkWeekHrs
False    11276
True       122
Name: count, dtype: int64

WorkPlan
WorkPlan
False    11277
True       121
Name: count, dtype: int64

WorkChallenge
WorkChallenge
False    11234
True       164
Name: count, dtype: int64

WorkRemote
WorkRemote
False    11390
True         8
Name: count, dtype: int64

WorkLoc
WorkLoc
False    11366
True        32
Name: count, dtype: int64

ImpSyn
ImpSyn
False    11393
True         5
Name: count, dtype: int64

CodeRev
CodeRev
False    11397
True         1
Name: count, dtype: int64

CodeRevHrs
CodeRevHrs
False    8972
True     2426
Name: count, dtype: int64

UnitTests
UnitTests
False    11369
True        29
Name: count, dtype: int64

PurchaseHow
PurchaseHow
False    11202
True       196
Name: count, dtype: int64

PurchaseWhat
PurchaseWhat
False    11360
True        38
Name: count, dtype: int64

LanguageWorkedWith
LanguageWorkedWith
False    11387
True        11
Name: count, dtype: int64

LanguageDesireNextYear
LanguageDesireNextYear
False    11264
True       134
Name: count, dtype: int64

DatabaseWorkedWith
DatabaseWorkedWith
False    10945
True       453
Name: count, dtype: int64

DatabaseDesireNextYear
DatabaseDesireNextYear
False    10356
True      1042
Name: count, dtype: int64

PlatformWorkedWith
PlatformWorkedWith
False    10987
True       411
Name: count, dtype: int64

PlatformDesireNextYear
PlatformDesireNextYear
False    10854
True       544
Name: count, dtype: int64

WebFrameWorkedWith
WebFrameWorkedWith
False    10005
True      1393
Name: count, dtype: int64

WebFrameDesireNextYear
WebFrameDesireNextYear
False    9781
True     1617
Name: count, dtype: int64

MiscTechWorkedWith
MiscTechWorkedWith
False    9216
True     2182
Name: count, dtype: int64

MiscTechDesireNextYear
MiscTechDesireNextYear
False    9943
True     1455
Name: count, dtype: int64

DevEnviron
DevEnviron
False    11369
True        29
Name: count, dtype: int64

OpSys
OpSys
False    11364
True        34
Name: count, dtype: int64

Containers
Containers
False    11316
True        82
Name: count, dtype: int64

BlockchainOrg
BlockchainOrg
False    9076
True     2322
Name: count, dtype: int64

BlockchainIs
BlockchainIs
False    8788
True     2610
Name: count, dtype: int64

BetterLife
BetterLife
False    11300
True        98
Name: count, dtype: int64

ITperson
ITperson
False    11363
True        35
Name: count, dtype: int64

OffOn
OffOn
False    11360
True        38
Name: count, dtype: int64

SocialMedia
SocialMedia
False    11105
True       293
Name: count, dtype: int64

Extraversion
Extraversion
False    11378
True        20
Name: count, dtype: int64

ScreenName
ScreenName
False    10891
True       507
Name: count, dtype: int64

SOVisit1st
SOVisit1st
False    11073
True       325
Name: count, dtype: int64

SOVisitFreq
SOVisitFreq
False    11393
True         5
Name: count, dtype: int64

SOVisitTo
SOVisitTo
False    11397
True         1
Name: count, dtype: int64

SOFindAnswer
SOFindAnswer
False    11395
True         3
Name: count, dtype: int64

SOTimeSaved
SOTimeSaved
False    11348
True        50
Name: count, dtype: int64

SOHowMuchTime
SOHowMuchTime
False    9481
True     1917
Name: count, dtype: int64

SOAccount
SOAccount
False    11397
True         1
Name: count, dtype: int64

SOPartFreq
SOPartFreq
False    10270
True      1128
Name: count, dtype: int64

SOJobs
SOJobs
False    11392
True         6
Name: count, dtype: int64

EntTeams
EntTeams
False    11393
True         5
Name: count, dtype: int64

SOComm
SOComm
False    11398
Name: count, dtype: int64

WelcomeChange
WelcomeChange
False    11313
True        85
Name: count, dtype: int64

SONewContent
SONewContent
False    9433
True     1965
Name: count, dtype: int64

Age
Age
False    11111
True       287
Name: count, dtype: int64

Gender
Gender
False    11325
True        73
Name: count, dtype: int64

Trans
Trans
False    11275
True       123
Name: count, dtype: int64

Sexuality
Sexuality
False    10856
True       542
Name: count, dtype: int64

Ethnicity
Ethnicity
False    10723
True       675
Name: count, dtype: int64

Dependents
Dependents
False    11258
True       140
Name: count, dtype: int64

SurveyLength
SurveyLength
False    11379
True        19
Name: count, dtype: int64

SurveyEase
SurveyEase
False    11384
True        14
Name: count, dtype: int64

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [18]:
# your code goes here
df['WorkLoc'].value_counts()

WorkLoc
Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: count, dtype: int64

Identify the value that is most frequent (majority) in the WorkLoc column.

In [2]:
#make a note of the majority value here, for future reference
# office is the most frequest one on the office

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [19]:
# your code goes here
df['WorkLoc'].replace(np.nan, 'office', inplace=True)

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [35]:
# your code goes here
missing_data = df.isnull()
print (missing_data['WorkLoc'].value_counts())  
print('')
print (df['WorkLoc'].value_counts())

WorkLoc
False    11398
Name: count, dtype: int64

WorkLoc
Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
office                                              32
Name: count, dtype: int64

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq". 

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [36]:
# your code goes here
df['CompFreq'].value_counts()

CompFreq
Yearly     6073
Monthly    4788
Weekly      331
Name: count, dtype: int64

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

In [38]:
# your code goes here
normal_annual_comp = []
for i in range(len(df)):
    if df['CompFreq'].iloc[i] == 'Weekly':
        normal_annual_comp.append(df['CompTotal'].iloc[i]*52)
    elif df['CompFreq'].iloc[i] == 'Monthly':
        normal_annual_comp.append(df['CompTotal'].iloc[i]*12)
    else:
        normal_annual_comp.append(df['CompTotal'].iloc[i])
df['NormalizedAnnualCompensation'] = normal_annual_comp
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase,NormalizedAnnualCompensation
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy,61000.0
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult,138000.0
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy,90000.0
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult,348000.0
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy,90000.0

In [45]:
df['NormalizedAnnualCompensation'].median()

100000.0

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

 Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).